name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-build:

    permissions:
      contents: read

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash"
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21, 25]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-java-${{ matrix.java }}
      cancel-in-progress: true
    name: "Build with Java ${{ matrix.java }}"
    env:
      DEFAULT_JAVA: 17

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Cache SonarQube packages
      if: ${{ env.DEFAULT_JAVA == matrix.java }}
      uses: actions/cache@v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-java-${{ matrix.java }}-sonar
        restore-keys: ${{ runner.os }}-java-${{ matrix.java }}-sonar

    - name: Build with Java ${{ matrix.java }} with configuration cache
      run: ./gradlew build --warning-mode all --exclude-task ossIndexAudit -PenableConfigurationCache=true -PjavaVersion=${{ matrix.java }}

    - name: Build with Java ${{ matrix.java }} without configuration cache
      # Required to get jacoco test coverage reports for SonarQube, which doesn't work with configuration cache enabled, see https://github.com/gradle/gradle/issues/25979
      run: ./gradlew clean build --warning-mode all --exclude-task ossIndexAudit -PenableConfigurationCache=false -PjavaVersion=${{ matrix.java }}

    - name: Upload reports
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        name: reports-java-${{ matrix.java }}
        path: build/reports/

    - name: Sonar analysis
      if: ${{ env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: ./gradlew sonar --info --warning-mode all -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ossindex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Ossindex
      run: ./gradlew ossIndexAudit --warning-mode all --info
      env:
        ORG_GRADLE_PROJECT_ossIndexUsername: ${{ secrets.OSSINDEX_USERNAME }}
        ORG_GRADLE_PROJECT_ossIndexToken: ${{ secrets.OSSINDEX_TOKEN }}

  build:
    needs:
      - matrix-build
      - ossindex
    runs-on: ubuntu-slim
    steps:
      - run: echo "Build successful"
